name: not defteri
markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions:
    - hard_wrap
    - autolink
    - no_intra_emphasis
    - fenced_code_blocks
    - tables
    - with_toc_data
pygments: false
url: http://queeup.github.io